"""init member table

Revision ID: 3d041896a038
Revises:
Create Date: 2025-07-13 15:59:49.114707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d041896a038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=False),
    sa.Column('urlreport', sa.String(), nullable=True),
    sa.Column('pin', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_index(op.f('ix_member_ipaddress'), 'member', ['ipaddress'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_ipaddress'), table_name='member')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
