"""fixing field name password_hash to password

Revision ID: 6b5fb04fcd56
Revises: 40e838eae069
Create Date: 2025-07-14 22:11:05.258582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b5fb04fcd56"
down_revision: Union[str, Sequence[str], None] = "40e838eae069"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=100), nullable=False))
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_hash", sa.VARCHAR(length=100), nullable=False)
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
