"""chore database

Revision ID: aa7b846ae6c6
Revises:
Create Date: 2025-07-14 17:59:06.787568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa7b846ae6c6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("ipaddress", sa.String(length=45), nullable=False),
        sa.Column("urlreport", sa.String(length=255), nullable=True),
        sa.Column("pin", sa.String(length=10), nullable=False),
        sa.Column("password", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    op.create_index(
        op.f("ix_members_ipaddress"), "members", ["ipaddress"], unique=False
    )
    op.create_index(op.f("ix_members_name"), "members", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_members_name"), table_name="members")
    op.drop_index(op.f("ix_members_ipaddress"), table_name="members")
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_table("members")
    # ### end Alembic commands ###
