"""adding balance field to member

Revision ID: c84e7be3f909
Revises: 6b5fb04fcd56
Create Date: 2025-07-15 19:28:55.547243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84e7be3f909'
down_revision: Union[str, Sequence[str], None] = '6b5fb04fcd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'balance')
    # ### end Alembic commands ###
